{% set version = "1.0.0" %}

package:
  name: zdnn 
  version: {{ version }} 

source:
  git_url: https://github.com/IBM/zDNN.git
  git_tag: v{{ version }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  
    - make
test:
  commands:
    - test -f ${PREFIX}/lib/libzdnn.a
    - test -f ${PREFIX}/lib/libzdnn.so
    - test -f ${PREFIX}/include/zdnn.h

about:
  home: https://github.com/IBM/zDNN
  license: Apache-2.0 license
  license_file: LICENSE
  summary: IBM Z Deep Neural Network Library (zDNN)
  description: |
    IBM Z Deep Neural Network Library provides an interface
    for applications making use of Neural Network Processing Assist Facility.
  doc_url: https://github.com/IBM/zDNN
  doc_source_url: https://github.com/IBM/zDNN/blob/main/README.md
  dev_url: https://github.com/IBM/zDNN

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
